# Taps
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'homebrew/cask-fonts'
tap 'ankitpokhrel/jira-cli' # JIRA
tap 'hashicorp/tap'
tap 'bufbuild/buf'
tap 'ankitpokhrel/jira-cli' # JIRA

# Brews
brew 'bat'
tap 'hashicorp/tap'
tap 'bufbuild/buf'
brew 'age'
brew 'ansible'
brew 'bat'
brew 'buf'
brew 'crane'
brew 'elixir'
brew 'fd'
brew 'ffmpeg'
brew 'fzf'
brew 'fd'
brew 'gh'
brew 'git'
brew 'go'
brew 'rust'
brew 'grpc'
brew 'jq'
brew 'k3d'
brew 'graphviz'
brew 'hey'
brew 'hugo'
brew 'hyperkit'
brew 'ipcalc'
brew 'iperf'
brew 'jira-cli'
brew 'jq'
brew 'k3d'
brew 'k6'
brew 'ko'
brew 'kubectl'
brew 'minikube'
brew 'mkcert'
brew 'neovim', args: ['HEAD']
brew 'newsboat'
brew 'nmap'
brew 'node'
brew 'podman'
brew 'protoc-gen-go-grpc'
brew 'ripgrep'
brew 'terraform'
brew 'terraform-ls'
brew 'tig'
brew 'tree'
brew 'watch'
brew 'zoxide'
brew 'mas'
brew 'iterm2'
brew 'notion'
brew 'jira-cli'

# Casks
cask 'alacritty'
cask 'docker'
cask 'firefox'
cask 'google-cloud-sdk'
cask 'brave-browser'
cask 'firefox'
cask 'google-cloud-sdk'
cask 'iina'
cask 'maccy'
cask 'obs'
cask 'osquery'
cask 'signal'
cask 'whatsapp'
cask 'slack'
cask 'tableplus'
cask 'transmission'
cask 'utm'
cask 'whatsapp'
cask 'zoom'
cask 'lens'
cask 'kap'
cask 'alfred'
cask 'raycast'
cask 'iina'
cask 'google-drive'
cask 'fig'
# cask 'adobe-creative-cloud'
cask 'goland'
cask 'visual-studio-code'
cask 'spotify'

# Fonts
cask 'font-fira-code'
cask 'font-fira-code-nerd-font'

# App Store
mas "Copy'em", id: 876540291
mas "Tailscale", id: 1475387142
