# Taps
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'homebrew/cask-fonts'
tap 'ankitpokhrel/jira-cli' # JIRA

# Brews
brew 'bat'
brew 'fzf'
brew 'fd'
brew 'gh'
brew 'git'
brew 'go'
brew 'rust'
brew 'grpc'
brew 'jq'
brew 'k3d'
brew 'kubectl'
brew 'minikube'
brew 'mkcert'
brew 'neovim'
brew 'nmap'
brew 'node'
brew 'protoc-gen-go'
brew 'protoc-gen-go-grpc'
brew 'ripgrep'
brew 'terraform'
brew 'tig'
brew 'tree'
brew 'watch'
brew 'zoxide'
brew 'mas'
brew 'iterm2'
brew 'notion'
brew 'jira-cli'

# Casks
cask '1password'
cask 'alacritty'
cask 'docker'
cask 'firefox'
cask 'google-cloud-sdk'
cask 'osquery'
cask 'signal'
cask 'whatsapp'
cask 'slack'
cask 'tableplus'
cask 'transmission'
cask 'whatsapp'
cask 'zoom'
cask 'lens'
cask 'kap'
cask 'alfred'
cask 'raycast'
cask 'iina'
cask 'google-drive'
cask 'fig'
# cask 'adobe-creative-cloud'
cask 'goland'
cask 'visual-studio-code'
cask 'spotify'

# Fonts
cask 'font-fira-code'
cask 'font-fira-code-nerd-font'

# App Store
mas "Copy'em", id: 876540291
mas "Tailscale", id: 1475387142
